'use strict';

/**
 * Raze mapping — PROPOSED, NOT CONFIRMED.
 *
 * Generated by `raze infer` from this database's own schema and the field
 * paths present in real captured Razorpay deliveries. Every line below has
 * evidence attached. Read it, correct anything that does not match what these
 * events mean for your business, and commit it.
 *
 * Inference can see that a column named order_id holds a Razorpay order id. It
 * cannot see whether a refund should reverse a balance or only mark a status.
 * Wherever that judgement was needed it is listed as a QUESTION rather than
 * decided silently.
 */

module.exports = function mappings(rz) {

  // key: "chaos_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'authorized' for payment.authorized
  // guard: refuse when "status" is already paid or refunded
  rz.map("payment.authorized", {
    "table": "chaos_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "authorized"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "chaos_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'paid' for payment.captured
  // add: "credited_paise" (bigint) += payload.payment.entity.amount
  // add: "credit_count" += 1 per applied capture
  // guard: refuse when "status" is already refunded
  rz.map("payment.captured", {
    "table": "chaos_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "paid"
      }
    },
    "add": {
      "credited_paise": "payload.payment.entity.amount",
      "credit_count": {
        "literal": 1
      }
    },
    "guard": {
      "column": "status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "chaos_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'paid' for order.paid
  // guard: refuse when "status" is already refunded
  rz.map("order.paid", {
    "table": "chaos_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "paid"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "chaos_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'refunded' for refund.created
  // QUESTION: a refund sets the status but reverses no amount — decide whether it should
  rz.map("refund.created", {
    "table": "chaos_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "refunded"
      }
    },
    "add": {},
    "guard": null,
    "insertIfMissing": true
  });

  // key: "chaos_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'failed' for payment.failed
  // guard: refuse when "status" is already paid or refunded
  rz.map("payment.failed", {
    "table": "chaos_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "failed"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "demo_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'authorized' for payment.authorized
  // guard: refuse when "status" is already paid or refunded
  rz.map("payment.authorized", {
    "table": "demo_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "authorized"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "demo_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'paid' for payment.captured
  // add: "credited_paise" (bigint) += payload.payment.entity.amount
  // add: "credit_count" += 1 per applied capture
  // guard: refuse when "status" is already refunded
  rz.map("payment.captured", {
    "table": "demo_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "paid"
      }
    },
    "add": {
      "credited_paise": "payload.payment.entity.amount",
      "credit_count": {
        "literal": 1
      }
    },
    "guard": {
      "column": "status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "demo_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'paid' for order.paid
  // guard: refuse when "status" is already refunded
  rz.map("order.paid", {
    "table": "demo_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "paid"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "demo_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'refunded' for refund.created
  // QUESTION: a refund sets the status but reverses no amount — decide whether it should
  rz.map("refund.created", {
    "table": "demo_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "refunded"
      }
    },
    "add": {},
    "guard": null,
    "insertIfMissing": true
  });

  // key: "demo_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'failed' for payment.failed
  // guard: refuse when "status" is already paid or refunded
  rz.map("payment.failed", {
    "table": "demo_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "failed"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "learn_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'authorized' for payment.authorized
  // guard: refuse when "status" is already paid or refunded
  rz.map("payment.authorized", {
    "table": "learn_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "authorized"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "learn_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'paid' for payment.captured
  // add: "credited_paise" (bigint) += payload.payment.entity.amount
  // add: "credit_count" += 1 per applied capture
  // guard: refuse when "status" is already refunded
  rz.map("payment.captured", {
    "table": "learn_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "paid"
      }
    },
    "add": {
      "credited_paise": "payload.payment.entity.amount",
      "credit_count": {
        "literal": 1
      }
    },
    "guard": {
      "column": "status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "learn_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'paid' for order.paid
  // guard: refuse when "status" is already refunded
  rz.map("order.paid", {
    "table": "learn_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "paid"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "learn_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'refunded' for refund.created
  // QUESTION: a refund sets the status but reverses no amount — decide whether it should
  rz.map("refund.created", {
    "table": "learn_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "refunded"
      }
    },
    "add": {},
    "guard": null,
    "insertIfMissing": true
  });

  // key: "learn_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'failed' for payment.failed
  // guard: refuse when "status" is already paid or refunded
  rz.map("payment.failed", {
    "table": "learn_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "failed"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "map_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'authorized' for payment.authorized
  // guard: refuse when "status" is already paid or refunded
  rz.map("payment.authorized", {
    "table": "map_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "authorized"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "map_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'paid' for payment.captured
  // add: "credited_paise" (bigint) += payload.payment.entity.amount
  // add: "credit_count" += 1 per applied capture
  // guard: refuse when "status" is already refunded
  rz.map("payment.captured", {
    "table": "map_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "paid"
      }
    },
    "add": {
      "credited_paise": "payload.payment.entity.amount",
      "credit_count": {
        "literal": 1
      }
    },
    "guard": {
      "column": "status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "map_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'paid' for order.paid
  // guard: refuse when "status" is already refunded
  rz.map("order.paid", {
    "table": "map_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "paid"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "map_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'refunded' for refund.created
  // QUESTION: a refund sets the status but reverses no amount — decide whether it should
  rz.map("refund.created", {
    "table": "map_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "refunded"
      }
    },
    "add": {},
    "guard": null,
    "insertIfMissing": true
  });

  // key: "map_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'failed' for payment.failed
  // guard: refuse when "status" is already paid or refunded
  rz.map("payment.failed", {
    "table": "map_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "failed"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "orders.razorpay_order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "payment_status" = 'authorized' for payment.authorized
  // guard: refuse when "payment_status" is already paid or refunded
  rz.map("payment.authorized", {
    "table": "orders",
    "key": {
      "column": "razorpay_order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "payment_status": {
        "literal": "authorized"
      }
    },
    "add": {},
    "guard": {
      "column": "payment_status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "orders.razorpay_order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "payment_status" = 'paid' for payment.captured
  // add: "total_paise" (bigint) += payload.payment.entity.amount
  // add: "applied_count" += 1 per applied capture
  // guard: refuse when "payment_status" is already refunded
  rz.map("payment.captured", {
    "table": "orders",
    "key": {
      "column": "razorpay_order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "payment_status": {
        "literal": "paid"
      }
    },
    "add": {
      "total_paise": "payload.payment.entity.amount",
      "applied_count": {
        "literal": 1
      }
    },
    "guard": {
      "column": "payment_status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "orders.razorpay_order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "payment_status" = 'paid' for order.paid
  // guard: refuse when "payment_status" is already refunded
  rz.map("order.paid", {
    "table": "orders",
    "key": {
      "column": "razorpay_order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "payment_status": {
        "literal": "paid"
      }
    },
    "add": {},
    "guard": {
      "column": "payment_status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "orders.razorpay_order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "payment_status" = 'refunded' for refund.created
  // QUESTION: a refund sets the status but reverses no amount — decide whether it should
  rz.map("refund.created", {
    "table": "orders",
    "key": {
      "column": "razorpay_order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "payment_status": {
        "literal": "refunded"
      }
    },
    "add": {},
    "guard": null,
    "insertIfMissing": true
  });

  // key: "orders.razorpay_order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "payment_status" = 'failed' for payment.failed
  // guard: refuse when "payment_status" is already paid or refunded
  rz.map("payment.failed", {
    "table": "orders",
    "key": {
      "column": "razorpay_order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "payment_status": {
        "literal": "failed"
      }
    },
    "add": {},
    "guard": {
      "column": "payment_status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "shop_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'authorized' for payment.authorized
  // guard: refuse when "status" is already paid or refunded
  rz.map("payment.authorized", {
    "table": "shop_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "authorized"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "shop_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'paid' for payment.captured
  // add: "credited_paise" (bigint) += payload.payment.entity.amount
  // add: "credit_count" += 1 per applied capture
  // guard: refuse when "status" is already refunded
  rz.map("payment.captured", {
    "table": "shop_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "paid"
      }
    },
    "add": {
      "credited_paise": "payload.payment.entity.amount",
      "credit_count": {
        "literal": 1
      }
    },
    "guard": {
      "column": "status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "shop_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'paid' for order.paid
  // guard: refuse when "status" is already refunded
  rz.map("order.paid", {
    "table": "shop_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "paid"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "refunded"
      ]
    },
    "insertIfMissing": true
  });

  // key: "shop_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'refunded' for refund.created
  // QUESTION: a refund sets the status but reverses no amount — decide whether it should
  rz.map("refund.created", {
    "table": "shop_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "refunded"
      }
    },
    "add": {},
    "guard": null,
    "insertIfMissing": true
  });

  // key: "shop_orders.order_id" (text) <- payload.payment.entity.order_id, names the Razorpay order
  // set: "status" = 'failed' for payment.failed
  // guard: refuse when "status" is already paid or refunded
  rz.map("payment.failed", {
    "table": "shop_orders",
    "key": {
      "column": "order_id",
      "from": "payload.payment.entity.order_id"
    },
    "set": {
      "status": {
        "literal": "failed"
      }
    },
    "add": {},
    "guard": {
      "column": "status",
      "notIn": [
        "paid",
        "refunded"
      ]
    },
    "insertIfMissing": true
  });
};
