'use strict';

/**
 * The conversation that sets a merchant up.
 *
 * A merchant arrives with two things: a database and a pair of Razorpay keys.
 * They are not expected to know what a webhook is, what idempotency means, or
 * which of their columns Raze needs. They answer questions; Raze does the rest.
 *
 * WHY THIS IS A STATE MACHINE AND NOT A MODEL
 *
 * Onboarding decides what gets written to a merchant's database. Every step here
 * is deterministic: the same answers produce the same integration, every time,
 * and the sequence can be read start to finish by whoever has to trust it. The
 * model answers questions about payments — it does not decide what to install.
 *
 * Each step returns a card: something to say, and at most one thing to do. The
 * merchant sees one question at a time and the proof of the last one, which is
 * the whole of the interface.
 */

const path = require('path');

const RAZE = path.join(__dirname, '..', '..');

/**
 * The next thing to ask, given what is already known.
 *
 * Order matters and is not arbitrary: nothing can be read from Razorpay without
 * keys, nothing can be mapped without a schema, and nothing may be armed before
 * a human has confirmed the mapping.
 */
function nextStep(state) {
  if (!state.razorpay_ok) {
    return {
      id: 'keys',
      say: "I'll look after your Razorpay payments — making sure every payment that "
        + "actually happened ends up in your database, and telling you when one doesn't.\n\n"
        + "To start I need your Razorpay **Test Mode** keys. Dashboard → Settings → API Keys.",
      fields: [
        { name: 'keyId', label: 'Key ID', placeholder: 'rzp_test_...' },
        { name: 'keySecret', label: 'Key secret', type: 'password' },
      ],
      action: 'Connect',
      note: 'Held in memory for this session. Never written to disk, never logged, never '
        + 'returned by any endpoint.',
    };
  }

  if (!state.database_ok) {
    return {
      id: 'database',
      say: "Connected. Now your application's database — the one with your orders in it.\n\n"
        + "Read-only credentials are enough for this step. PostgreSQL only, which is a real "
        + "limitation rather than a preference.",
      fields: [
        { name: 'databaseUrl', label: 'Connection string', type: 'password',
          placeholder: 'postgres://user:pass@host:5432/dbname' },
      ],
      action: 'Read my schema',
      note: 'Raze cannot discover a database on your private network, and will not try. '
        + 'Everything after this it works out for itself.',
    };
  }

  if (!state.mapping_confirmed) {
    return { id: 'mapping', say: null, dynamic: true };
  }

  if (state.escalate_only === null || state.escalate_only === undefined) {
    return {
      id: 'sideEffects',
      say: "One thing I can't tell from your schema: **does marking an order paid trigger "
        + "anything else in your application** — an email, a shipment, a fulfilment hook?",
      choices: [
        { value: 'yes', label: "Yes, or I'm not sure" },
        { value: 'no', label: 'No, it only changes the row' },
      ],
      note: 'If it does, I will never repair an order on my own — I will always ask you '
        + 'first. Repairing something that fires a shipment could send it twice.',
    };
  }

  if (!state.refund_policy) {
    return {
      id: 'refund',
      say: "And on a refund: should the money come back out of the order's amount, or "
        + "should only the status change?",
      choices: [
        { value: 'status', label: 'Status only' },
        { value: 'subtract', label: 'Also subtract the amount' },
      ],
      note: 'Status only keeps the order amount meaning what the customer was charged, '
        + 'which is what I compare against Razorpay.',
    };
  }

  if (!state.backfill_at) {
    return {
      id: 'backfill',
      say: "That's everything I need. Let me check the last 24 hours against Razorpay so "
        + "you get a real number rather than a promise.",
      action: 'Check the last 24 hours',
    };
  }

  return { id: 'done', say: null };
}

/**
 * The integration, written out for the merchant to keep.
 *
 * Raze does not need this file to work — it applies the mapping itself. It
 * exists because a merchant should be able to see, in their own stack's terms,
 * exactly what has been installed on their behalf, and take it with them if they
 * ever stop using Raze.
 */
function buildIntegration({ table, key, status, credited, expected, ordersDescription }) {
  return `'use strict';

/**
 * Razorpay webhook integration — generated by Raze for this merchant.
 *
 * You do not have to run this file. Raze applies the same mapping itself, in one
 * transaction per delivery, and this is what it does written out in code you own.
 *
 * What it guarantees, precisely:
 *
 *   Exactly one business-state transition per Razorpay event, within Raze's
 *   transactional boundary. A delivery that arrives twice — and Razorpay will
 *   send up to 16 across nearly a day — applies once.
 *
 * What it does not:
 *
 *   Anything outside that transaction. If your application sends an email when
 *   an order becomes paid, that email is yours to make idempotent.
 */

const express = require('express');
const raze = require('raze/src/runtime');
const mapping = require('raze/src/mapping');

module.exports = async function mountRazorpayWebhook(app, pool) {
  const rz = raze.create({
    db: pool,
    webhookSecret: process.env.RAZORPAY_WEBHOOK_SECRET,
  });

  const m = mapping.attach(rz, pool);

  // Your orders live in "${table}". ${ordersDescription || ''}
  await m.map('payment.captured', {
    table: '${table}',
    key: { column: '${key}', from: 'payload.payment.entity.order_id' },
    set: { ${status}: { literal: 'paid' } },
    add: { ${credited}: 'payload.payment.entity.amount' },
    // Never move an order backwards, and never credit a refunded one.
    guard: { column: '${status}', notIn: ['refunded'] },
    // A webhook never invents an order that does not exist.
    insertIfMissing: false,
  });

  await m.map('payment.failed', {
    table: '${table}',
    key: { column: '${key}', from: 'payload.payment.entity.order_id' },
    set: { ${status}: { literal: 'failed' } },
    guard: { column: '${status}', notIn: ['paid', 'refunded'] },
    insertIfMissing: false,
  });

  await m.map('refund.created', {
    table: '${table}',
    key: { column: '${key}', from: 'payload.payment.entity.order_id' },
    set: { ${status}: { literal: 'refunded' } },
    insertIfMissing: false,
  });

  // The raw body matters: the signature is computed over exactly these bytes,
  // and re-serialising the JSON would break verification.
  app.use('/webhook', express.raw({ type: () => true }), rz.middleware());

  return rz;
};
${expected ? `
// Raze checks every payment against "${expected}" before repairing anything
// unattended. Without that check it would settle an order for an amount nobody
// verified.
` : `
// This merchant has no column recording what an order should cost, so Raze
// reports divergence but never repairs unattended — there is nothing to check a
// payment against.
`}`;
}

module.exports = { nextStep, buildIntegration };
